site_name: Dharmamitra Documentation
site_url: https://dharmamitra.github.io/dharmamitra-guides/
site_description: >
  Guides and tutorials for the Dharmamitra meta-platform: open-source NLP,
  OCR, search and translation tools for Sanskrit, Pāli, Classical Chinese
  and Tibetan. Detailed documentation of the DharmaNexus platform and datasets.
use_directory_urls: true
theme:
  name: material
  logo: assets/mitra-logo-header.png
  palette:
    primary: 'custom'
# Added a comment to trigger a rebuild
plugins:
  - search
  - sitemap
nav:
  - 'Home': 'index.md'
  - 'Acknowledgments': 'acknowledgments.md'
  - 'MITRA Tools':
    - 'Overview': 'mitra_tools/index.md'
    - 'Translate': 'mitra_tools/translate.md'
    - 'Sanskrit Grammar': 'mitra_tools/sanskrit_grammar.md'
    - 'OCR': 'mitra_tools/ocr.md'
    - 'Search': 'mitra_tools/search.md'
    - 'Deep Research': 'mitra_tools/deep_research.md'
  - 'MITRA Browser Extensions': 'mitra_browser_extensions.md'
  - 'MITRA Dictionaries': 'mitra_dictionaries.md'
  - 'MITRA Emacs Extensions': 'emacs_extensions.md' 
  - 'MITRA Models': 'mitra_models.md'
  - 'DharmaNexus': 'dharmanexus.md'  
  - 'Datasets': 'datasets.md'
  - 'Publications': 'publications.md'
  - 'Presentations': 'presentations.md'
  - 'History': 'history.md'
  - 'Frequently Asked Questions': 'faq.md'
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - meta 