site_name: Dharmamitra Guides
theme:
  name: material
  logo: assets/mitra-logo-header.png
  palette:
    primary: 'custom'
repo_url: https://github.com/dharmamitra/dharmamitra-guides
nav:
  - 'Home': 'index.md'
  - 'DharmaNexus': 'dharmanexus.md'
  - 'MITRA Tools': 'mitra_tools.md'
  - 'MITRA Dictionaries': 'mitra_dictionaries.md'
  - 'MITRA Models': 'mitra_models.md'
  - 'Publications': 'publications.md'
extra_css:
  - stylesheets/extra.css 