site_name: Dharmamitra Documentation
theme:
  name: material
  logo: assets/mitra-logo-header.png
  palette:
    primary: 'custom'
repo_url: https://github.com/dharmamitra/dharmamitra-guides
# Added a comment to trigger a rebuild
nav:
  - 'Home': 'index.md'
  - 'MITRA Tools': 'mitra_tools.md'
  - 'MITRA Browser Extensions': 'mitra_browser_extensions.md'
  - 'MITRA Dictionaries': 'mitra_dictionaries.md'
  - 'MITRA Models': 'mitra_models.md'
  - 'DharmaNexus': 'dharmanexus.md'  
  - 'Datasets': 'datasets.md'
  - 'Publications': 'publications.md'
  - 'Presentations': 'presentations.md'
  - 'History': 'history.md'
  - 'Frequently Asked Questions': 'faq.md'
extra_css:
  - stylesheets/extra.css 